---
# tasks file for roles/mariadb_verdes

  - name: Mariadb server install
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - mariadb-server
      - mariadb-client
      - python3-pip

  - name: Install PyMySQL with pip
    pip:
      name: PyMySQL
      executable: pip3
      extra_args: --user

  - name: Mariadb service enable and start
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: Configure mariadb to listen on all interfaces
    lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^bind-address'
      line: bind-address = 0.0.0.0
    notify: Restart mariadb server

  - name: Open mariadb ports
    ufw:
     rule: allow
     port: '3306'
     proto: tcp

#MySQL Secure Installation
  - name: Update MariaDB root password
    mysql_user:
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_user: root
      login_password: root
      check_implicit_admin: yes
      name: root
      host: "{{ item }}"
      password: root
    loop:
      - 127.0.0.1
      - localhost
      - 192.168.0.%

  - name: Delete anonymous user
    mysql_user:
      login_host: localhost
      login_user: root
      login_password: root
      name: ""
      host_all: yes
      state: absent

  - name: Delete test database
    mysql_db:
      login_host: localhost
      login_user: root
      login_password: root
      name: test
      state: absent
