---
- name: Tareas Generales en Servidores Linux
  hosts: linux
  become: yes
  remote_user: ansible

  tasks:
  - name: Update RedHat Servers
    yum:
      name: "*"
      state: latest
    notify: Restart
    when: ansible_os_family == "RedHat"

  - name: Update Debian Servers
    apt:
      name: "*"
      state: latest
      update_cache: yes
    notify: Restart
    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart
    reboot:

- name: Configuracion de Servidores RedHad
  hosts: redhat
  become: yes
  remote_user: ansible

  roles:
    - geerlingguy.apache
    - container_tomcat

  tasks:

  - name: Open firewall ports
    firewalld: 
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    loop:
    - http
    - https

  - name: Create virtualhost configuration directory
    file:
      path: /etc/httpd/vhosts.d
      state: directory
      owner: root

  - name: Copy virtualhost configuration
    copy:
      src: roles/geerlingguy.apache/files/virtualhost.conf
      dest: /etc/httpd/vhosts.d/ejemplo.conf
    notify: Restart apache

  - name: Include vhosts directory
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      line: IncludeOptional /etc/httpd/vhosts.d/*.conf

  handlers:

  - name: Restart apache
    service:
      name: httpd
      state: restarted

- name: Configuracion de Servidores Debian
  hosts: debian
  become: yes
  remote_user: ansible

  roles:
    - mariadb_verdes
    - create.database
